### ISSUE TITLE
Paths appear to be hardcoded in 0.3a, causing failures

### ISSUE THREAD

**Issue by blockfeed** [emoose/iQueTool#1]
In 0.3a, some paths appear to be hardcoded and it causes normal commands to fail due to perceived missing files. 

> iQueTool.exe nand -x -xk nand.bin
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ique\(ique\nands\_orig\24.3.18 evening\nand.bin_ext\crl.sys'.

This behavior is not present in 0.3 and it works properly.

iQueTool 0.3: iQue Player file manipulator
Opening NAND image from nand.bin...
[!] No output path (-o) given, set path to:
- nand.bin_ext
<program works properly>

Let me know if you need any additional info.

**Comment by Jhynjhiruu** [comment]
Seems like emoose is temporarily dead, so probably avoid iQueTool if you can...
